---
plugin: amazon.aws.aws_ec2

# Kaunse AWS Region mein scan karna hai
regions:
  - ap-south-1

# Filter: Sirf wo instances uthao jo running hon aur Role=web, Env=dev ho
filters:
  instance-state-name: running
  "tag:Role": web
  "tag:Env": dev

# Hostname in inventory: web-1, web-2 (taaki website pe sahi hostname render ho)
hostnames:
  - tag:Name

# 'web' group automatically create karo taaki site.yml aur group_vars bilkul pehle jaise kaam karein
groups:
  web: "tags['Role'] | default('') == 'web'"

# SSH connection settings (Private IP se connect hoga)
compose:
  ansible_host: private_ip_address
  ansible_user: "'ubuntu'"